[tool.poetry]
name = "structcheck"
version = "1.0.0"
description = ""
authors = ["vincentBenet <vincent.benet@outlook.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
unittest = "^0.0"
pylint = "^2.15.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
"Homepage" = "https://github.com/pypa/structcheck"
"Bug Tracker" = "https://github.com/pypa/structcheck/issues"
"Author" = "https://github.com/vincentBenet"
