[tool.poetry]
name = "structcheck"
version = "1.0.0"
description = ""
authors = ["vincentBenet <vincent.benet@outlook.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
unittest = "^0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
